language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - php artisan asset:generate --env=testing
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_success:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.5" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.5" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
